name: Randomizer
version: '${version}'
load: STARTUP
main: de.gamdude.randomizer.Randomizer
api-version: 1.20

commands:
  state:
    description: Set state of the game
    usage: ยง7Use /state <start/stop/pause>
    permission: randomizer.state
